### PR TITLE
Updated Readme

### PR DESCRIPTION
**Pull request by isyneha**
Added a contributor Section in the Readme file which will show the list of all the contributors you have contributed in the repository.

### CODE REVIEW

**Comment by Lynch23** [comment]
Hello Sneha, thank you for your many contributions to the repo, I will go ahead and merge the the PR and Happy Coding!

**Comment by isyneha** [comment]
You are welcome. Happy Coding!

**Comment by isyneha** [comment]
@Lynch23 Could you please add hacktoberfest-accepted label in this?

**Comment by Lynch23** [comment]
Hello Sneha, can you confirm if the label has been added?

**Pull request merged**
